#!/usr/bin/bash

# Sources ".profile" for restic specific variables,
# otherwise termux-job-scheduler won't parse them.
source /data/data/com.termux/files/home/.profile

# Parses possible errors into $ERROR to later pipe it to termux-notification
ERROR+=$((restic unlock --quiet) 2>&1)

# Only files or directories specified in ".dir_list.txt" are backed-up
ERROR+=$((restic backup --files-from .dir_list.txt --tag mi9tpro --no-scan --quiet) 2>&1)
ERROR+=$((restic check --quiet) 2>&1)

# Modify to customize restic snapshots retention policy
ERROR+=$((restic forget --prune --keep-daily 30 --keep-monthly 12 --keep-yearly 3 --quiet) 2>&1)

if [ -z "$ERROR" ];
then
    # Outputs an android notification if backup and repo check were successful
    termux-notification --icon "done" -t "Restic backup successful"
else
    # Outputs an android notification if any restic command reported an error,
    # and pareses the output to the notification body
    termux-notification --icon "warning" -t "Restic backup error" -c "$ERROR" --button1 "Retry?" --button1-action ./data/data/com.termux/files/home/termux_backup
fi