#!/usr/bin/bash

# Sources ".profile" for restic variables
source /data/data/com.termux/files/home/.profile

# Parses possible errors into $ERROR
ERROR+=$((restic unlock --quiet) 2>&1)

# Files or directories specified in ".dir_list.txt" are backed-up
ERROR+=$((restic backup --files-from .dir_list.txt --tag mi9tpro --no-scan --quiet) 2>&1)
ERROR+=$((restic check --quiet) 2>&1)

# Modify to customize restic snapshots retention policy
ERROR+=$((restic forget --prune --keep-daily 30 --keep-monthly 12 --keep-yearly 3 --quiet) 2>&1)

if [ -z "$ERROR" ];
then
    # Android notification if both backup and repo check were successful
    termux-notification --icon "done" -t "Restic backup successful"
else
    # Android notification if any of the previous commands reported an error
    termux-notification --icon "warning" -t "Restic backup error" -c "$ERROR" --button1 "Retry?" --button1-action ./data/data/com.termux/files/home/restic-backup
fi